// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4QeFnYSWt2VuXihE_tWbCwS0IZIt2A7E',
    appId: '1:228572729109:web:c605b536e43d1a4e6ca31c',
    messagingSenderId: '228572729109',
    projectId: 'edusakha-5fe8f',
    authDomain: 'edusakha-5fe8f.firebaseapp.com',
    storageBucket: 'edusakha-5fe8f.appspot.com',
    measurementId: 'G-2DE795ZC4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZjpVr4f1ipLNolb8jCtezHWuyez6c4pg',
    appId: '1:228572729109:android:30831e965a5a160f6ca31c',
    messagingSenderId: '228572729109',
    projectId: 'edusakha-5fe8f',
    storageBucket: 'edusakha-5fe8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9-leEYrhTmev4VYUzbhT8fWs2dc8FhXo',
    appId: '1:228572729109:ios:02462f8b8e7ea29a6ca31c',
    messagingSenderId: '228572729109',
    projectId: 'edusakha-5fe8f',
    storageBucket: 'edusakha-5fe8f.appspot.com',
    androidClientId: '228572729109-or92p3ao9bl76a3u9asmj06i956jt9c0.apps.googleusercontent.com',
    iosClientId: '228572729109-jgebgvqblqq37mbbcl05a6hqin2ohcpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.edusakha',
  );
}
